version: '3.8'

services:
  index:
    build: .
    container_name: index-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - webnet

  server:
    build: .
    container_name: server-container
    ports:
      - "8101:8101" 
    volumes:
      - ./src/server:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge